services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${GREENLIGHT_DB_DATABASE}
      POSTGRES_USER: ${GREENLIGHT_DB_USERNAME}
      POSTGRES_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - psql_volume:/var/lib/postgresql/data

  api:
    image: golang:1.23
    working_dir: /app
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
        go install github.com/air-verse/air@latest &&
        make watch/api
      "
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git/
            - .gitignore

volumes:
  psql_volume:
  go-modules:
