FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache make git ca-certificates

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

ENTRYPOINT ["air", "-c", ".air.toml"]
