FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod go mod download

ENTRYPOINT ["air", "-c", ".air.toml"]
